### PR TITLE
Updated Notes and getGAlignmentsData()

### PR DESCRIPTION
**Pull request by rosachoe**

### CODE REVIEW

**Comment by seandavi** [comment]
Looks great!  I’ll fix this detail, but just a note that external data has a specific place.  I can explain the next time we are together, but here is some basic documentation:

http://r-pkgs.had.co.nz/data.html#data-extdata http://r-pkgs.had.co.nz/data.html#data-extdata

Sean

**Comment by rosachoe** [comment]
Oh, okay, so the .bam and Setup.R files should go in inst/extdata?

**Comment by rosachoe** [comment]
or inst/extdata?

**Comment by seandavi** [comment]
Everything in “inst” will get installed into the “top-level” package directory.  The “extdata” directory is really meant for “raw data”.  If you have scripts, I’d consider putting those in inst/scripts for now.  We probably can do away with that later, but that is where I’d stick it for now. Don’t stress too much about it.  We can easily move things around.

Sean

**Pull request merged**
